services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    environment:
      SATQUERY_B2_BASE_URL: http://b2:8100
      SATQUERY_CONFIDENCE_BASE_URL: http://b2:8100
      SATQUERY_ML_BASE_URL: http://mock-ml:8200
    ports:
      - "8000:8000"
    depends_on:
      - b2
      - mock-ml

  b2:
    build:
      context: .
      dockerfile: Dockerfile.b2
    ports:
      - "8100:8100"

  mock-ml:
    build:
      context: .
      dockerfile: Dockerfile.ml
    ports:
      - "8200:8200"
