"""
SatQuery AI — Model Configuration

Central configuration for all model paths, hyperparameters, and service settings.
Edit this file to customize for your hardware and data setup.
"""

import os
from pathlib import Path


# =============================================================================
# Base Paths
# =============================================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
MODELS_DIR = PROJECT_ROOT / "models"
CHECKPOINTS_DIR = PROJECT_ROOT / "checkpoints"
DOCS_DIR = PROJECT_ROOT / "docs"

# =============================================================================
# Model Paths
# =============================================================================

# InternVL2-2B base model (downloaded from HuggingFace)
INTERNVL2_MODEL_PATH = str(MODELS_DIR / "InternVL2-2B")
INTERNVL2_HF_NAME = "OpenGVLab/InternVL2-2B"

# LoRA adapter (created after fine-tuning)
LORA_ADAPTER_PATH = str(CHECKPOINTS_DIR / "satquery-lora" / "final")

# Grounding DINO (downloaded separately for grounding endpoint)
GROUNDING_DINO_MODEL = "IDEA-Research/grounding-dino-base"

# =============================================================================
# Dataset Paths
# =============================================================================

# BigEarthNet.txt annotations
BIGEARTHNET_TXT_PARQUET = str(DATA_DIR / "bigearthnet_txt" / "BigEarthNet.txt.parquet")

# Training data (generated by data pipeline)
TRAINING_DATA_DIR = str(DATA_DIR / "training")
TRAIN_JSONL = str(DATA_DIR / "training" / "train.jsonl")
VAL_JSONL = str(DATA_DIR / "training" / "val.jsonl")

# BigEarthNet v2 imagery (LMDB format, if downloaded)
BIGEARTHNET_LMDB = str(DATA_DIR / "Encoded-BigEarthNet")

# =============================================================================
# Hardware Configuration (RTX 3060 6GB)
# =============================================================================

# Quantization
LOAD_IN_4BIT = True
BNB_4BIT_QUANT_TYPE = "nf4"
BNB_4BIT_COMPUTE_DTYPE = "bfloat16"
BNB_4BIT_DOUBLE_QUANT = True

# Memory management
FREEZE_VISION_ENCODER = True  # ALWAYS True for 6GB
GRADIENT_CHECKPOINTING = True  # Essential for training on 6GB
MAX_DYNAMIC_PATCH = 6  # Limit tile count (default 12 is too much)

# =============================================================================
# LoRA Configuration
# =============================================================================

LORA_R = 8
LORA_ALPHA = 16
LORA_DROPOUT = 0.05
LORA_TARGET_MODULES = ["wqkv", "wo"]  # InternLM2: fused QKV + output proj

# =============================================================================
# Training Configuration
# =============================================================================

TRAIN_EPOCHS = 3
TRAIN_BATCH_SIZE = 1  # MUST be 1 for 6GB VRAM
GRADIENT_ACCUMULATION = 8  # Effective batch size = 8
LEARNING_RATE = 2e-4
MAX_SEQ_LENGTH = 1024
OPTIMIZER = "paged_adamw_8bit"
SEED = 42

# =============================================================================
# Service Configuration
# =============================================================================

SERVICE_HOST = "0.0.0.0"
SERVICE_PORT = 8001
MAX_NEW_TOKENS = 512
TEMPERATURE = 0.1  # Low temp for factual answers

# =============================================================================
# Normalization Stats (Official BigEarthNet v2 training split)
# =============================================================================

S2_BAND_MEANS = {
    "B01": 361.077, "B02": 438.372, "B03": 614.056, "B04": 588.410,
    "B05": 942.843, "B06": 1769.932, "B07": 2049.552, "B08": 2193.292,
    "B8A": 2235.557, "B09": 2241.455, "B11": 1568.227, "B12": 997.732,
}

S2_BAND_STDS = {
    "B01": 575.069, "B02": 607.027, "B03": 603.297, "B04": 684.569,
    "B05": 738.433, "B06": 1100.456, "B07": 1275.805, "B08": 1369.372,
    "B8A": 1356.544, "B09": 1316.393, "B11": 1070.161, "B12": 813.528,
}

S1_STATS = {
    "VV": {"mean": -12.644, "std": 5.133},
    "VH": {"mean": -19.353, "std": 5.591},
}
